In [ ]:
print("Hello, world")

In [2]:
print(1+1)

2


In [4]:
num =12
name= 'Sam'

In [6]:
print('My number is {} and my name is {}'.format(num,name))

My number is 12 and my name is Sam


In [7]:
s = 'abcdefghijk'

In [10]:
s[:3]

'abc'

In [11]:
s[0:3]

'abc'

In [12]:
my_list = ['a','b','c','d']

In [13]:
my_list.append('d')

In [14]:
my_list

['a', 'b', 'c', 'd', 'd']

In [18]:
my_list[0]

'a'

In [16]:
my_list[1:3]

['b', 'c']

In [17]:
d = {'key1':'value','key2':123}

In [22]:
d['Key1']

'value'

In [23]:
d['key2']

123

In [27]:
d =  {'K1':[1,2,3]}

In [28]:
d

{'K1': [1, 2, 3]}

In [29]:
1 == 2

False

In [30]:
1 == 1

True

In [31]:
1 !=3

True

In [34]:
(1 < 2) or (2 > 3)

True

In [35]:
if 1 <2:
    print('yep')

yep


In [36]:
i = 1
while i < 5:
    print("i is: {}".format(i))
    i = i + 1

i is: 1
i is: 2
i is: 3
i is: 4


In [38]:
for x in range(0, 5): 
    print(x)

0
1
2
3
4


In [40]:
x = [1, 2, 3, 4]
out = []
for num in x:
    out.append(num ** 2)

In [41]:
print(out)

[1, 4, 9, 16]


In [43]:
def my_func(name="Default Name"):
    print("Hello " + name)

In [44]:
my_func()

Hello Default Name


In [45]:
def square(num):
    return num ** 2

output = square(2) 

In [46]:
output

4

In [47]:
def square(num):
    """
    This is the docstring.
    This function squares a number.
    """
    return num ** 2

In [48]:
output

4

In [49]:
square

<function __main__.square(num)>

In [51]:
seq = [1, 2, 3, 4, 5]

In [53]:
list(filter(lambda num: num % 2 == 0, seq))

[2, 4]

In [55]:
s = 'Hello my name is Sam'

In [56]:
s.lower()

'hello my name is sam'

In [57]:
s.upper()

'HELLO MY NAME IS SAM'

In [58]:
s.split()

['Hello', 'my', 'name', 'is', 'Sam']

In [59]:
tweet = 'Go Sport! #Sports'

In [60]:
tweet.split('#')[1]

'Sports'

In [63]:
x = [(1, 2), (3, 4), (5, 6)]

In [64]:
for a, b in x:
    print(a)   # prints 1, 3, 5
    print(b)   # prints 2, 4, 6

1
2
3
4
5
6


In [65]:
my_list = [1,2,3]

In [66]:
import numpy as np

In [67]:
np.array(my_list)

array([1, 2, 3])

In [69]:
arr = np.array(my_list)

In [70]:
arr

array([1, 2, 3])

In [71]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [72]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])